Section "InputClass"
    Identifier "Synaptics touchpad local"
    MatchIsTouchpad "on"
    MatchDriver "synaptics"
    MatchDevicePath "/dev/input/event*"

    # Tap: 1 dedo=izq, 2 dedos=der, 3 dedos=medio
    Option "TapButton1" "1"
    Option "TapButton2" "3"
    Option "TapButton3" "2"

    # Scroll con 2 dedos
    Option "VertTwoFingerScroll" "1"
    Option "HorizTwoFingerScroll" "1"

    # Scroll “natural” (invertido): valores negativos
    Option "VertScrollDelta" "-80"
    Option "HorizScrollDelta" "-80"

    # Inercia (coasting)
    Option "CornerCoasting" "0"
    Option "CoastingSpeed" "20"
    Option "CoastingFriction" "50"
EndSection