# Fuente como Ghostty
font_family Cascadia Code
font_size 10

# Terminal
term xterm-kitty
allow_remote_control socket-only

# Tema rofi-adi1090x
foreground #ffffff
background #1e1e1e
cursor #2e6f40
cursor_text_color #1e1e1e
selection_foreground #1e1e1e
selection_background #2e6f40

# Transparencia estilo rofi
background_opacity 0.92

# Look plano y con aire
hide_window_decorations yes
window_padding_width 10

# Scroll mas rapido
wheel_scroll_multiplier 5.0

# Keybindings personalizados
map ctrl+shift+f show_scrollback
map ctrl+c copy_or_interrupt
map ctrl+backspace send_text all \x1b\x7f
map ctrl+delete send_text all \x1bd
map ctrl+left send_text all \x1bb
map ctrl+right send_text all \x1bf
